### ISSUE TITLE
Настройка SASS синтаксиса

### ISSUE THREAD

**Issue by veremey** [dmitry-lavrik/smart-grid#1]
Было бы удобнее, если для SASS сгенерированный файл имел вид *_smart-grid.sass*, а не *smart-grid.sass* в таком виде его проще вставить в свои стили и генерировать все сразу.

**Comment by veremey** [comment]
Так как ко мне писали с такой проблемой, отпишу:
С SASS синтаксисом заморачиваться вообще не нужно, тут все просто в файле, в котором генерируете ставите **@import smart-grid**  (проверьте правильность пути у себя) все что нужно сделать это правильно настроить **gulpfile.js** например:

> var smartgridSettings = {
>     outputStyle: 'sass', /* less || scss || sass || styl */
>     columns: 24, /* number of grid columns */
>     offset: "12px", /* gutter width px || % */
>     container: {
>         maxWidth: '1092px', /* max-width оn very large screen */
>         fields: '12px' /* side fields */
>     },
>     breakPoints: {
>         lg: {
>             'width': '1000px', /* -> @media (max-width: 1100px) */
>             'fields': '12px' /* side fields */
>         },
>         md: {
>             'width': '960px',
>             'fields': '15px'
>         },
>         sm: {
>             'width': '780px',
>             'fields': '15px'
>         },
>         xs: {
>             'width': '660px',
>             'fields': '15px'
>         }
>     }
> };
> 
> gulp.task('smartgrid', function() {
>     smartgrid('../static/css/sass', smartgridSettings);
> });
> 
> gulp.task('sass', function() {
>     var processors = [
>         autoprefixer({browsers: ['IE 9', 'IE 10', 'IE 11', 'Opera 12', 'iOS 7', 'last 5 versions'], cascade: false}),
>         mqpacker({
>             sort: function (a, b) {
>                 a = a.replace(/\D/g,'');
>                 b = b.replace(/\D/g,'');
>                 return b-a;
>             }
>         })
>     ];
>     return sass(config.src.sass+'**/*.sass', {
>         sourcemap: false,//true is better
>         // style: 'compact',
>         style: 'compressed',
>         emitCompileError: true
>     })
>     .on('error', notify.onError({
>         title: 'Sass Error!',
>         message: '<%= error.message %>'
>     }))
>     .pipe(postcss(processors))
>     .pipe(sourcemaps.write('./'))
>     .pipe(gulp.dest(config.dest.css));
> });
> 
> gulp.task('sass:watch', function() {
>     gulp.watch(config.src.sass + '**/*', ['sass']);
> });

**Comment by dmitry-lavrik** [comment]
В версию 1.0.1 добавлю в settings возможность переименования файла.

**Comment by veremey** [comment]
Было бы хорошо отсортировать переменные по порядку:  =wrapper(), =row-flex(), =row-float(), =offset($n), =justify-content($value), а уже после 'col-()' и все что с ним связано - сейчас немного сложно в поиске переменных.

**Comment by ekstrimal94** [comment]
Здравствуйте! Для smart-grid нужен свой компилятор? Если да скажите пожалуйста как его поставить?

**Comment by dmitry-lavrik** [comment]
В версию 1.0.1 добавил возможность переименовать файл. Например:

var settings = {
    filename: '_smart-grid'
};

**Comment by maxlanser** [comment]
покажите пример как егоиспользовать sass синтаксисе, потом как в описании я так понял что приведён для Stylus

**Comment by maxlanser** [comment]
Если вы его установили через npm, то для начала нужно сгенерировать саму библиотеку  в формате SASS, SCSS, Less или Stylus. Для этого в  документации показано что для этого нужно создать файл допустим **`smart-grid.js`**  с содержанием которое так же для примера приведено в документации где и можете указать все необходимые настройки под ваш проект, и в самом низу так же можете увидеть вызов данного скрипта для генерации библиотека с указанием места назначения куда его сохранить `smartgrid('./path-to-your-folder', settings);`. После того как создали этот файл, откройте в этой же папке коммандную строку и просто выполните команду `node smat-grid.js`  
После этого сгенерируется файл в выбранном вами формате в указанное вами место. Что касается его дальнейшего использования и импортирования то это зависит от выбранного формата, как импортировать его в свои стили думаю вы найдете инфу...
