### ISSUE TITLE
Добавить миксин, скрывающий блок на определённых разрешениях

### ISSUE THREAD

**Issue by imgsrc** [dmitry-lavrik/smart-grid#10]
Было бы здорово, если какому-нибудь блоку можно было задавать миксин типа
`+hidden-md()`

**Comment by shurinskiy** [comment]
А кто мешает, этому же блоку задать .md(display, none);?

**Comment by dmitry-lavrik** [comment]
Да, верно, +md(display, none) ничем не хуже +hidden-md().

Сейчас собираю дополнительные идеи для версии smart-grid 2.0.0 - описание в видео - https://youtu.be/BLsldt8fYOM
