### ISSUE TITLE
Отвратительный мануал

### ISSUE THREAD

**Issue by itechnocrat** [dmitry-lavrik/smart-grid#11]
Никогда не встречал проектов на GitHub с таким же скудным описанием.
Как будто специально написано так мало, чтоб ничего было непонятно.
Ни слова не сказано как работает плагин, а он, как выяснилось, даже не "пайпится".
Не сказано как указать исходный (обрабатываемый) файл.
Непонятно толком о каком файле идет речь в параметре вызова smartgrid.
Очень небрежно и неуважительно к людям.

**Comment by kovtunos** [comment]
Проект в opensource. Если хочешь, возьми и помоги написать мануал.

**Comment by akulyk** [comment]
Автор все очень доступно разжевал и в рот положил в видео на youtube. Это первое.
Второе, он и не должен "пайпиться". У него задача сгенерировать файл на заданном препроцессоре для последующей работы.

**Comment by kovtunos** [comment]
> У него задача сгенерировать файл на заданном препроцессоре для последующей работы.
Файл, сгенерированный smart-grid является по сути набором миксинов.

**Comment by itechnocrat** [comment]
Люди, вы ничего не объясняете, а повторятете то, что непонятно.
Мануал я смогу написать тогда, когда увижу и пойму как все это работает, не раньше.
Как я должен был узнать, что есть видео? Нет ссылок в мануале.
Непонятно, почему оно не должен пайпиться, но ладно, это дело десятое, но просто, как все работает можно же написать.
Внимание, вопросы:
какой файл ест плагин, как находит, как его указать?
в какой файл попадает выхлоп?
правильно ли я понял из ответов, что выхлоп надо в свою очередь пропускать через препроц-р (sass)?
какое имеет отношение к моим вопросам путь к файлу в вызове -
smartgrid('./path-to-your-folder', settings); ?

**Comment by kovtunos** [comment]
1. У тебя есть var settings = {...} из README. Кастомизируешь его, как тебе нужно.
Указываешь имя выходного файла, используемый препроцессор, брейкпойнты etc.

2. Создаёшь gulp task, к примеру: smartgrid:
`gulp.task('smartgrid', () => smartgrid('папка куда положить миксины', smartgridSettings));`

3. Выполняешь в консоли `gulp smartgrid`.
В соответствующую папку будет сгенерирован файл с миксинами.

4. Подключаешь файл с миксинами в препроцессоре.

5. Профит.

**Comment by itechnocrat** [comment]
Большое спасибо, добрый человек!
1. Тут все вроде бы понятно, кроме указания имени выходного файла - это какой параметр?
2. За это отдельное спасибо, если будет работать. )
3. Ясно.
4. А я знаю, что надо делать `@import или @include` в какой-то файл, это обязательно и для чего или об этом и речь, и это для подключения готового файла с миксинами для обработки препроцессором?

P.S.
Название переменной изменить стоит, согласен, а то не кошерно.

Канал Алексея Климанова "аграгрегра" я знаю, до 7-го джедая верстки дошел, gulp юзаю без особых проблем, добавляю пакеты, редактирую gulpfile.js и т.д., но я не могу понять в каком файле я должен набирать подобное:
```
.items{
    .row-flex();
    .justify-content-md(center);

    .item{
        .col();
        .col-3();
        .col-md-5();
        .col-xs-10();
    }
}
```
и как эта приблуда найдет этот файл?
Обяснишь?

**Comment by kovtunos** [comment]
Я думаю, проще показать на примере. Вот пример gulp таска с рабочего проекта:

```
const gulp = require('gulp'),
smartgrid  = require('smart-grid');

const smartgridSettings = {
  outputStyle: 'scss',
  columns: 12, // number of grid columns
  offset: '15px', // gutter width px || %
  filename: '_smart-grid',
  container: {
    maxWidth: '1170px', // max-width оn very large screen
    fields: '15px' // side fields
  },
  breakPoints: {
    xlg: {
      'width': '1600px',
      'fields': '15px'
    },
    lg: {
      'width': '1200px',
      'fields': '15px'
    },
    md: {
      'width': '992px',
      'fields': '15px'
    },
    sm: {
      'width': '768px',
      'fields': '15px'
    },
    xs: {
      'width': '544px',
      'fields': '15px'
    },
    xxs: {
      'width': '420px',
      'fields': '15px'
    }
  }
};

gulp.task('smartgrid', () => smartgrid('./src/scss/mixins', smartgridSettings));
```

> я не могу понять в каком файле я должен набирать подобное

В файлах стилей (scss, sass, styl): 
Данный код для препроцессора Less. Дмитрий его использует в своих видео. В Sass все миксины будут с @include, в Stylus, просто как функции, без точки.

Пример для scss с рабочего проекта:

```
.footer__block {
  @include col-3;
  @include col-md-6;
  @include col-sm-12;

  &:nth-child(1),
  &:nth-child(2) {
    @include col-sm-6;

    @include breakpoint(max-width 500px) {
      @include col-xs-12;
    }
  }
}
```

Используется подход Desktop-first, т.е. в медиавыражениях генерируется условие с max-width (не min-width).

Надеюсь, так понятно.

Сейчас Дмитрий добавил новый миксин size(). Можно указывать size(4) вместо col-4. 
Все миксины можно посмотреть в сгенерированном файле (в моём случае src/scss/mixins/_smart-grid.scss).
