### ISSUE TITLE
Сетка без отступов между колонками

### ISSUE THREAD

**Issue by enkos** [dmitry-lavrik/smart-grid#14]
Можно ли добавить примесь чтобы генерировать сетку без отступов между колонками?

что-то типо этого
```sass
=row-flex-no-gutter()
```

Пример из бутстрапа
https://v4-alpha.getbootstrap.com/layout/grid/#no-gutters

**Comment by dmitry-lavrik** [comment]
Да, такая вещь в процессе создания в версии 2.0.0.

Сейчас собираю дополнительные идеи для версии smart-grid 2.0.0 - описание в видео - https://youtu.be/BLsldt8fYOM

**Comment by rom4uk** [comment]
В примесь .debug можно добавить какой-то z-index? Иначе он не перекрывает другие элементы, у которых position: fixed.

**Comment by rebroff** [comment]
Так появился в версии 2 такой миксин?

**Comment by pashkes** [comment]
@rebroff я так понял появилась возможность это делать глобально в файле с настройками, а вот чисто чтоб миксином это делать вроде нельзя. Тоже вот нужно было сбросить отступ именно для нескольких блоков

**Comment by dmitry-lavrik** [comment]
Есть небольшая проблема.

Когда была версия 1, то добавить в ней примесь вида .col(@offset: @offset) не составляло труда.

А вот в версии 2 было внедрено новшество, которое многие просили, - смена отступов на брейкпоинтах.

И из-за этого теперь примеси .row-*, .col, .shift-* ориентируются на ряд переменных для каждого брейкпоинта, на котором offset меняется. Поэтому передавать в них один offset не получится. Именно это в ветке 2 затормозило создание примеси, принимающей offset в качестве параметра.

Если нужно, чтобы у блоков не было отступов, то есть пара вариантов.

1. Использовать .col-padding. Да, там будет отступ, но фоны будут соприкасаться, что подходит почти всегда
2. Вообще не использовать .row и .col. display: flex для строки, примеси .size для столбцов.

**Comment by SergeyLitvin** [comment]
Спасибо за "пару вариантов". А то я сам как то не додумался. Для блоков где нужно было получить соприкасающиеся фоны я  пользовался просто display: flex. А так можно пользоваться примесями, что очень удобно.

**Comment by shurinskiy** [comment]
Первый вариант, не сработает если содержимым блоков сетки будут картинки, которые должны будут соприкасаться без зазора, в соседних блоках. Средствами смартгрид, эта задача не решается. 

Второй вариант, не сработает потому, что даже если не будет примесей .row и .col - примеси .size, все равно будут рассчитывать ширину блока с учетом зашитого в настройках отступа. Колонки будут уже чем надо и справа будет пустота, даже при .size(24)

**Comment by dmitry-lavrik** [comment]
Может так подойдёт? - https://github.com/dmitry-lavrik/smart-grid/releases/tag/v.2.1.2
