### ISSUE TITLE
2 и более свойств в .md( );

### ISSUE THREAD

**Issue by StarBurstx** [dmitry-lavrik/smart-grid#15]
.md(background, black);
.md(font-size, 30px);

Есть ли синтаксис группировки? Когда допустим нужно указать для 2 и более свойств для .md

**Comment by dmitry-lavrik** [comment]
.md-block({
    background: black;
    font-size: 30px;
});

**Comment by StarBurstx** [comment]
Дмитрий, спасибо! Этот проект - просто шедевр!
