### ISSUE TITLE
Улучшения синтаксиса миксинов для stylus

### ISSUE THREAD

**Issue by g-rodigy** [dmitry-lavrik/smart-grid#18]
Посмотрел сгенерированный файлик, для миксинов медиа запросов можно сделать вариант укороченного синтаксиса http://stylus-lang.com/docs/mixins.html#block-mixins
например можно так  как в примере ниже, гараздо удобнее чем писать  `sm/sm-block({ //styles })`
``` 
+sm()
    // some styles
    // some styles
```

**UPD**
Еще в **sm-block()** нельзя вставить **&** , stylus ругается(может это только у меня)

**Comment by dmitry-lavrik** [comment]
Я только за, но это поломает обратную совместимость версий, поэтому такое изменение будет при глобальном обновлении, например, создании версии 3.

**Comment by g-rodigy** [comment]
Отлично, осталось только ждать

**Comment by dmitry-lavrik** [comment]
Внедрил такой синтаксис в сетку 2.1

**Comment by dmitry-lavrik** [comment]
https://github.com/dmitry-lavrik/smart-grid/releases/tag/v.2.1.1
