### ISSUE TITLE
Рекомендую поправить расчет сетки. 

### ISSUE THREAD

**Issue by veremey** [dmitry-lavrik/smart-grid#2]
Рекомендую поправить
`width: #{calc(4.166666666666667% - #{$offset})}`     на  
`width: #{calc(100%/24 - #{$offset})}`
Кому приходиться править такой код - неприлично ругается.

**Comment by dmitry-lavrik** [comment]
width: #{calc(100%/24 - #{$offset})} даст на выходе calc(100% / 24 - 30px)

Т.е, мы выносит 100% / 24 на стороны браузера, что не выглядит правильным.

**Comment by dmitry-lavrik** [comment]
Кстати, интересная тема.

Я в ветке 2.0.0 сделал именно схему именно calc(100% / collums * n - offset). Но! IE11 тогда страшно глючит: на каких-то пикселях норм показывает, на каких-то всё слетает.

Поэтому в ветке 2.0.1 по умолчанию генерятся жуткие проценты, как и было раньше. В духе calc(33.333333334% - 30px). Они работают надёжно, даже в IE 11.

При этом есть флажок detailedCalc, если его поставить в true, то будет схема calc(100% / collums * n - offset). Её можно использовать, если на IE 11 пофигу.

**Comment by weissfl** [comment]
А почему в файле настроек этой настройки нет?

**Comment by dmitry-lavrik** [comment]
В файле system/defaults/settings.js последнее поле detailedCalc: false

https://github.com/dmitry-lavrik/smart-grid/blob/master/system/defaults/settings.js
