### ISSUE TITLE
Конфликт имен с библиотекой Bourbon

### ISSUE THREAD

**Issue by rebroff** [dmitry-lavrik/smart-grid#20]
Здравствуйте.
В популярной библиотеке Bourbone есть миксин size(), что приводит к конфликту имен (назовем это так) при совместном использовании со smart-grid. Приходится на каждом проекте редактировать сгенерированный smart-grid.scss, что не очень удобно, не говоря уже о том, что человек, знакомый со smart-grid, который будет поддерживать код в дальнейшем, ожидает size(), а не size-default(), как сейчас у меня.

**Comment by g-rodigy** [comment]
В конфиге можно указать имена для миксинов
` smartGrid(__dirname, {
    mixinNames: {
        size: 'my-size'
    }
});`

**Comment by rebroff** [comment]
Благодарю.
