### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by lavodka** [dmitry-lavrik/smart-grid#23]
Здравствуйте. 
Когда будет v2 Stable version?

**Comment by Tierey** [comment]
можно заменить имена  "md-block" на "md"  a "md(1,2)" на что-то другое или вообще выпилить ... эт реально важно)  или какнить там в mixinNames:  настройку этого добавить ( аля  block: "SIZE что то свое" SIZE интерполировать уже внутри под брейки. Было бы ок а то реплейсить из проекта в проект уже надоело). И в настройках где-то указать что не нужно генерить резет  и дебаг мелочь но уже почти идеал) Спасиб!

**Comment by pavelarseyev** [comment]
Судя по сгенерированному файлу, врапперфулл это примесь в которой рассчитываются паддинги в зависимости от выставленных настроек для всех медиазапросов. Потом этот враппер фул инклудится в примесь wrapper(), которая отвечает за центрирование и макс. ширину контейнера, а ее мы задаем фиксированным значением. Возможно задумка в том, чтобы разнести то по разным местам :)

**Comment by dmitry-lavrik** [comment]
Вышла ветка 2.1

**Comment by Tierey** [comment]
ченжлог? ютуб?

**Comment by dmitry-lavrik** [comment]
@Tierey , там ничего особенного, в 2.0.1 1 баг всего нашёлся, поправил.

Из важного только для stylus - https://github.com/dmitry-lavrik/smart-grid/releases/tag/v.2.1.1
