### ISSUE TITLE
Несколько сеток - сетка внутри сетки

### ISSUE THREAD

**Issue by mrScrpt** [dmitry-lavrik/smart-grid#25]
Подскажите пожалуйста. А можно ли сгенерировать несколько сеток с разным количеством колонок. Допустим у меня есть сетка из 12 колонок, в ней есть блок на 9 колонок. Дизайнер нарисовал внутри блока (который на 9 колонок) несколько блоков, но эти блоки стоят по общей сетке из 12 колонок, один из них занимает 2 колонки(общей сетки), но если я размечаю блок из 9 колонок примесью row-flex() то я получаю внутри сетку из 12 колонок(мои 9 колонок принимаются за 100% и делятся на 12) и я не могу выровнять внутри блоки по внешней сетке. Возможно можно сделать еще одну сетку на 9 колонок, вложить ее в блок из 9 колонок и получить внутри те же колонки что и снаружи. Возможно я что-то намудрил и это можно сделать проще?=) Если что простите

**Comment by pavelarseyev** [comment]
Ничего же не мешает сначала сгенерировать обычную сетку, а потом в настройки таска внести другое количество колонок, нужные отступы, поменять название примесей и сменить название генерируемого файла. В итоге получится две библиотеки для двух разных сеток. Останется заимпортить их и постараться не запутаться при их использовании :)

**Comment by mrScrpt** [comment]
@pavelarseyev ну это понятно, что так можно=)))))) Возможно есть способ нативный, а не костыльный=)
В любом случае оказалось куда проще просто самому разметить блок как нужно, а не тянуть ворох css кода для пустяковой задачи

**Comment by dmitry-lavrik** [comment]
Это перебор) Тут реально лучше вручную решить задачу, чем загромождать библиотеку такими возможностями.

**Comment by dmitry-lavrik** [comment]
В версии 2.1.2 что-то такое появилось - https://github.com/dmitry-lavrik/smart-grid/releases/tag/v.2.1.2
