### ISSUE TITLE
Поддежка offset в smart-grid 2.0 sass

### ISSUE THREAD

**Issue by webssea** [dmitry-lavrik/smart-grid#26]
Здравствуйте!, как прописать offset, пишу  "+offset-left-lg(3)" , но ничего не происходит помогите как нужно прописывать оффсет в smart-grid, припроцесор sass.

**Comment by webssea** [comment]
Решил откатом до версии 1.0.1, =)

**Comment by dmitry-lavrik** [comment]
Добрый день!

+shift-left-lg(3)

Либо переопределить mixinNames.
