### ISSUE TITLE
Ошибка в SCSS

### ISSUE THREAD

**Issue by rsm1985** [dmitry-lavrik/smart-grid#28]
При использовании миксина lg-block в SCSS возникает ошибка:
Миксин: @include lg-block(display:flex; margin-left: 21.5%);
Ошибка: 
Error: expected a variable name (e.g. $x) or ')' for the parameter list for lg-block
        on line 25 of dev/stylesheets/modules/_first-screen.scss
        @include lg-block(display:flex; margin-left: 21.5%);
   -------------------^

Что не так? 

Заранее благодарен.

**Comment by pavelarseyev** [comment]
А там разве не нужны фигурные скобки?
@include lg-block( =>{ display:flex; margin-left: 21.5% }<= );
