### ISSUE TITLE
Использование $content

### ISSUE THREAD

**Issue by mafreelancer** [dmitry-lavrik/smart-grid#29]
Довольно интересная сетка, прямо сейчас её использую.

Однако я столкнулся с проблемой

`lg-block($content)`
`----@media screen and (max-width: $break_lg)`
`---------{$content}`

Как в аргумент $content вставить несколько селекторов? Перепробовал все возможные варианты, в итоге получаю сообщение о синтаксических ошибках. Использую препроцессор Stylus.

**Comment by g-rodigy** [comment]
В этой версии только переписать сгенерированный смартгридом файлик под stylus {block}

**Comment by dmitry-lavrik** [comment]
Внедрил синтаксис 

+lg_block()
   code

в сетку 2.1

**Comment by dmitry-lavrik** [comment]
https://github.com/dmitry-lavrik/smart-grid/releases/tag/v.2.1.1
