### ISSUE TITLE
Как в примеси size() сделать max-width равным width?

### ISSUE THREAD

**Issue by dmitriy76** [dmitry-lavrik/smart-grid#30]
Если использовать сетку на флексах, и для айтема со значением, скажем, size(3) задавать `display: flex; flex-direction: column; flex-grow: 1;` - то за счет `flex-grow: 1;` блок, если он единственный в строке, растягивается не только по высоте, как нужно для верстки, но и по ширине.
Хорошо бы, чтобы примесь size() создавала два правила одновременно - width и max-width.

**Comment by bezdupel** [comment]
@dmitriy76 А разве без `flex-grow` блок по высоте не растягивается? Или для чего используется `flex-grow`?

**Comment by dmitry-lavrik** [comment]
Тут не то в плане flex-ов. Column текущего тега относится к детям этого тега, а flex-grow растягивает его в его же родителе, у которого нормальное направление row.
