### ISSUE TITLE
smart-grid webpack

### ISSUE THREAD

**Issue by FryOS** [dmitry-lavrik/smart-grid#31]
Можно ли настроить smart-grid под webpack ?
Если да, то можете показать как? Пример небольшой. 
Спасибо.

**Comment by dmitry-lavrik** [comment]
Нет, скорее webpack должен работать на уровне препроцессорного кода.

А под генерации smart-grid-ом препроцессорной библиотеки можно сделать отдельный файл, прописать там настройки и smart-grid(filename, options) и запускать его командой node.

Особых неудобств это не должно вызвать, всё-таки генерация библиотеки - операция намного более редкая, по сравнению с компиляцией препроцессорного кода в css.
