### ISSUE TITLE
Mobile-first для медиа-запросов

### ISSUE THREAD

**Issue by lipinart** [dmitry-lavrik/smart-grid#32]
Здравствуйте, Дмитрий. Очень нравиться то, что вы делаете. Смарт-грид вообще бомба избавляющая от лишней писанины. Единственное, что хотелось бы, опционально расставлять медиа-запросы в порядке MobileFirst. 
Сейчас приходится немного корректировать готовый смарт-грид файл, с миксинами Bootstrap4:
media-breakpoint-up / media-breakpoint-down

**Comment by dmitry-lavrik** [comment]
Добрый день!

А попробуйте опцию mobileFirst: true, она как раз поменяет все запросы с max-width на min-width.
