### ISSUE TITLE
* { Box-sizing: Border-box } 

### ISSUE THREAD

**Issue by Jorikkornev** [dmitry-lavrik/smart-grid#36]
Доброго времени суток! 
Может не совсем по теме, в reset-mixin добавить fix box-sizing

 /* apply a natural box layout model to all elements, but allowing components to change */
 html {   box-sizing: border-box; } 
*, *:before, *:after {   box-sizing: inherit; }

**Comment by dmitry-lavrik** [comment]
Добрый день! Это идея на любителя, не все привыкли к * border-box.

**Comment by andreyalexeich** [comment]
@Jorikkornev не рекомендуется использовать *, так как рендер веб-страницы идёт справа налево. Именно, кстати, поэтому рекомендуется указывать классы в html всему, по возможности
