### ISSUE TITLE
Проблема с row в SCSS

### ISSUE THREAD

**Issue by RomanOmelchenko** [dmitry-lavrik/smart-grid#4]
$offset: 30px;
$offset_one_side: ($offset / 2);

@mixin row-flex(){
    display: flex;
    flex-wrap: wrap;
    margin-left: $offset_one_side;
    margin-right: $offset_one_side;
}
@mixin row-float(){
    margin-left: $offset_one_side;
    margin-right: $offset_one_side;
    @include clearfix();
}

На препроцессоре SCSS в row передается значение с положительным margin.
Я то у себя создал новую переменную которая передает отрицательное значение, но это не удобно, приходится заново её объявлять после каждого нового запуска проекта. 
В общем такой баг :)

**Comment by dmitry-lavrik** [comment]
Большое спасибо! В версии 1.0.1 была допущена ошибка, исправил на ($offset_one_side * -1)

Версия 1.0.2 - глюк только в стилусе.

Версия 1.0.3 - всё исправлено. доступна на npmjs.

**Comment by RomanOmelchenko** [comment]
Супер, все работает.
