### ISSUE TITLE
Smart-grid.css ?

### ISSUE THREAD

**Issue by alvandyan** [dmitry-lavrik/smart-grid#42]
Добрый день! Установил smart-grid. Всё работает. Но, есть одно но. В настройках путь в проекте, куда добавить smart-grid. scss такой (src/scss) и он добавляет. Потом из папки scss файлы gulp переносит в build/css. Но, там кроме style.min.css появляется ещё и пустой файл smart-grid.css. Как от него избавиться?

**Comment by alvandyan** [comment]
> Добрый день! Установил smart-grid. Всё работает. Но, есть одно но. В настройках путь в проекте, куда добавить smart-grid. scss такой (src/scss) и он добавляет. Потом из папки scss файлы gulp переносит в build/css. Но, там кроме style.min.css появляется ещё и пустой файл smart-grid.css. Как от него избавиться?

**Comment by akavato** [comment]
smart-grid лишь генерирует стили, ничего никуда не копирует. Тут вопрос правильного использования gulp. Без gulpfile.js не разобраться
