### ISSUE TITLE
Неопознанный $val.

### ISSUE THREAD

**Issue by Anu2biZ** [dmitry-lavrik/smart-grid#43]
Здравствуйте! Использую gulp scss starter, где Ваш коллега импортировал smart grid.
Не могу использовать миксины size

Постоянно лезет ошибка
`>>     width: #{calc(#{$val} - #{$offset})};

   ---------------------------------------^

    messageOriginal: Undefined variable: "$val".
    relativePath: src\styles\vendor\import\_smart-grid.scss
`

Подскажите, пожалуйста, как это исправить. Заранее спасибо!

**Comment by sitnikovalex** [comment]
Таж самая ошибка, решения не нашел

**Comment by sitnikovalex** [comment]
> Здравствуйте! Использую gulp scss starter, где Ваш коллега импортировал smart grid.
> Не могу использовать миксины size
> 
> Постоянно лезет ошибка
> `>> width: #{calc(#{$val} - #{$offset})};
> 
> ---------------------------------------^
> 
> ```
> messageOriginal: Undefined variable: "$val".
> relativePath: src\styles\vendor\import\_smart-grid.scss
> ```
> 
> `
> 
> Подскажите, пожалуйста, как это исправить. Заранее спасибо!

в .stylelintrc добавить. Проблема с неверной сортировкой
` 
"ignoreFiles": [
        "./src/styles/vendor/import/_smart-grid.scss"
    ],
`
