### ISSUE TITLE
Mobile first

### ISSUE THREAD

**Issue by VovaRvUa** [dmitry-lavrik/smart-grid#44]
Еще не юзал скрипт, но так понимаю доступно только @media (max-width...), desktop first?
Как насчет mobile first?

**Comment by r13s** [comment]
Нужно изменить одну строку в конфиге:

https://github.com/dmitry-lavrik/smart-grid/blob/b1131d050bb42a6ba9012f847410c84d0321ef86/system/defaults/settings.js#L6

**Comment by dmitry-lavrik** [comment]
https://grid4web.ru/options/mobile-first
