### ISSUE TITLE
Выключить автогенерацию файла smart-grid

### ISSUE THREAD

**Issue by kovtunos** [dmitry-lavrik/smart-grid#5]
Привет, Дмитрий. На днях начал использовать smart-grid на одном проекте. 
Заметил, что по умолчанию файл перегенерируется при каждом старте gulp.
Может есть смысл добавить в конфиг параметр типа auto-generate: true/false?

**Comment by dmitry-lavrik** [comment]
Привет! А можно взглянуть на gulpfile? По-идее генерацию нужно вынести в отдельный таск, либо вообще в отдельный файл.

**Comment by kovtunos** [comment]
Да, действительно. Как-то не подумал об этом. Вынес генерацию в отдельный таск.
Спасибо за хорошую сетку. Нагляднее чем Susy, и флексбоксы рулят, конечно.
