### ISSUE TITLE
Описание, польза от незнаний нет.

### ISSUE THREAD

**Issue by Genrokku** [dmitry-lavrik/smart-grid#6]
По описанию не понятно, что и как. Прошу добавить инструкцию как пользоваться этим чудом, или хотя бы как её подключить. К примеру куда засунуть эти настройки( из вкладки **usege** ) или как подключить smart-grid. Описание действительно ужасное...

**Comment by ybeliaev** [comment]
лучше больше не отвечай. Показал что самый умный?

15 апреля 2017 г., 17:18 пользователь Tobira <notifications@github.com>
написал:

**Comment by kovtunos** [comment]
@Genrokku 
1. Поищи в Google по ключевым словам «Использование Gulp»
2. Посмотри внутрь сгенерированного файла smart-grid.sass и проанализируй содержимое.

**Comment by Genrokku** [comment]
@kovtunos 
Эмм, у меня лежит репозиторий с галпфайлом, соответсвенно - я умею им пользоваться. И в содержимом я тоже копался, и ничего это не дало, насколько я понял самртгид сам генерирует библиотеку, на основе сделаного мной файла-конфига, вот только как его сгенерить, и куда положить файлик, не понятно(

**Comment by kovtunos** [comment]
> я умею им пользоваться
1. Создай новый таск, назови его smartgrid;
2. вставь внутрь код с конфигом, модифицируй по собств. усмотрению;
3. запусти из консоли gulp smartgrid;
4. просмотри список миксинов в сгенерированном файле, и определи какие тебе нужны, какие нет (у Дмитрия достаточно видеоуроков, в которых он показывает примеры, какие миксины использовать, и для каких случаев);
5. пользуйся.

**Comment by Genrokku** [comment]
@kovtunos Cпасибо, все получилось)))

**Comment by Bakhtiyart** [comment]
ывафа

**Comment by astelit** [comment]
Дима, возможно я не замечаю и это реализовано уже, но мне не хватает сетки margin, например, как я это вижу: добавить условие в миксин :
1)
=wrapper($widht: 1200)
	@if($widht == full)
		+wrapper-full()
	@else
		max-width: $widht + px
		+wrapper-full()
		margin: 
			left: auto
			right: auto
2)
=size($n, $full: null)
  @if($full == full)
    $val: 100% / $columns * $n
    width: $val
  @else
    $val: 100% / $columns * $n
    width: #{calc(#{$val} - #{$offset})}
