### ISSUE TITLE
создать папку назначения автоматически

### ISSUE THREAD

**Issue by pepelxD** [dmitry-lavrik/smart-grid#7]
В smartgrid.js
`smartgrid('./dev/scss/grid', settings);`
Но если каталога нет, то выдает ошибку. Неплохо было бы создавать каталог автоматически

**Comment by libertyswift** [comment]
B плюсом сюда же возможность задавать имя сгенерированному файлу, было бы вообще здорово

**Comment by kovtunos** [comment]
> B плюсом сюда же возможность задавать имя сгенерированному файлу, было бы вообще здорово

Эта возможность есть уже давно:

`filename: '_smart-grid'`
