### ISSUE TITLE
генерировать wrapper-fluid (аналог container-fluid)

### ISSUE THREAD

**Issue by D3-FC** [dmitry-lavrik/smart-grid#8]
Парой необходим контейнер во всю ширину.
на текущий момент приходится делать костылёчек вида:
```
=wrapper-fluid()
  +wrapper
  max-width: none
```

Было бы здорово если бы wrapper-fluid был бы из коробки

**Comment by dmitry-lavrik** [comment]
В версии 2.0.0 уже запрогал.

Сейчас собираю дополнительные идеи для версии smart-grid 2.0.0 - описание в видео - https://youtu.be/BLsldt8fYOM
