### ISSUE TITLE
Параметр "condition"

### ISSUE THREAD

**Issue by webmaxx** [dmitry-lavrik/smart-grid#9]
В файле system/media.js есть такой кусок кода:
`function Media(breakPoint, device, condition)`
И тут есть параметр "condition", от которого, я так понимаю, зависит то, какой медиа-запрос будет генериться ("min-width" либо "max-width").
Только нет возможности его указать в конфиге, а очень хотелось бы? Или я не прав и такая возможность есть?

**Comment by akavato** [comment]
также было бы хорошо возможность указать ориентацию девайса. Например +sm-block-portrait

**Comment by dmitry-lavrik** [comment]
В версии 2.0.0 уже приготовил в конфиге mobileFirst и defaultMediaDevice.

Сейчас собираю дополнительные идеи для версии smart-grid 2.0.0 - описание в видео - https://youtu.be/BLsldt8fYOM
